plom_server/API/urls.py
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2023 Edith Coates
# Copyright (C) 2023-2025 Colin B. Macdonald

from django.urls import include, path
from rest_framework.routers import DefaultRouter, SimpleRouter

from .views.experimental import (
    RubricViewSet,
    AnnotationViewSet,
    MarkingTaskViewSet,
)

from .routes import (
    MarkURLPatterns,
    IdURLPatterns,
    PagedataPatterns,
    AnnotationPatterns,
    AnnotationImagePatterns,
    MiscURLPatterns,
    TagsURLPatterns,
)

from .views import (
    QuestionMarkingViewSet,
    # TODO: these are possibly temporary
    ScanListBundles,
    ScanBundleActions,
    ScanMapBundle,
    FinishReassembled,
    REPspreadsheet,
    REPidentified,
    REPcompletionStatus,
    REPcoverPageInfo,
)

from .views import MgetRubricMarkingTasks

"""
Handle URL patterns for the plom-client / server API.
See docs for including other URLconfs:
https://docs.djangoproject.com/en/4.2/topics/http/urls/#including-other-urlconfs

Note: The URL Patterns classes are made in order to seamlessly split up urls.py
across multiple files. In the future, once we're able to start changing the design
of the plom-client URLS, we ought to transition to using Django REST Framework
routers: https://www.django-rest-framework.org/api-guide/routers/
"""


urlpatterns = [
    path("", include(MiscURLPatterns.patterns())),
    path(MarkURLPatterns.prefix, include(MarkURLPatterns.patterns())),
    path(IdURLPatterns.prefix, include(IdURLPatterns.patterns())),
    path(PagedataPatterns.prefix, include(PagedataPatterns.patterns())),
    path(AnnotationPatterns.prefix, include(AnnotationPatterns.patterns())),
    path(AnnotationImagePatterns.prefix, include(AnnotationImagePatterns.patterns())),
    path(TagsURLPatterns.prefix, include(TagsURLPatterns.patterns())),
    # TODO: Issue #3786: eventually remove the "beta" from these provisional URLs
    path(
        "api/beta/scan/bundles",
        ScanListBundles.as_view(),
        name="api_Scan_bundles",
    ),
    path(
        "api/beta/scan/bundle/<int:bundle_id>",
        ScanBundleActions.as_view(),
        name="api_can_bundle_actions",
    ),
    # "api/beta/scan/bundle/<int:bundle_id>/map/<int:papernum>/<str:questions>",
    path(
        "api/beta/scan/bundle/<int:bundle_id>/<int:page>/map",
        ScanMapBundle.as_view(),
        name="api_Scan_bundle_map",
    ),
    path(
        "api/beta/finish/reassembled/<int:papernum>",
        FinishReassembled.as_view(),
        name="api_Finish_reassembled",
    ),
    path(
        "REP/spreadsheet",
        REPspreadsheet.as_view(),
        name="api_REP_spreadsheet",
    ),
    path(
        "REP/identified",
        REPidentified.as_view(),
        name="api_REP_identified",
    ),
    path(
        "REP/completionStatus",
        REPcompletionStatus.as_view(),
        name="api_REP_completion_status",
    ),
    path(
        "REP/coverPageInfo/<int:papernum>",
        REPcoverPageInfo.as_view(),
        name="api_REP_cover_page_info",
    ),
]

experimental_router = DefaultRouter(trailing_slash=True)
experimental_router.register("rubrics", RubricViewSet, basename="rubrics")
experimental_router.register("annotations", AnnotationViewSet, basename="annotations")
experimental_router.register(
    "marking-tasks", MarkingTaskViewSet, basename="marking-tasks"
)

marking_router = SimpleRouter(trailing_slash=False)
marking_router.register("tasks", QuestionMarkingViewSet, basename="tasks")

urlpatterns += [
    path("experimental/", include(experimental_router.urls)),
    path("MK/", include(marking_router.urls)),
    path(
        "rubrics/<int:rid>/tasks",
        MgetRubricMarkingTasks.as_view(),
        name="api_rubrics_tasks",
    ),
]

plom_server/QuestionTags/urls.py
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024 Elisa Pan

from django.urls import path
from .views import (
    QTagsLandingView,
    AddQuestionTagLinkView,
    CreateTagView,
    DeleteTagView,
    EditTagView,
    DownloadQuestionTagsView,
    ImportTagsView,
)

urlpatterns = [
    path("qtags/", QTagsLandingView.as_view(), name="qtags_landing"),
    path("add/", AddQuestionTagLinkView.as_view(), name="add_question_tag"),
    path("create/", CreateTagView.as_view(), name="create_tag"),
    path("delete/", DeleteTagView.as_view(), name="delete_tag"),
    path("edit/", EditTagView.as_view(), name="edit_tag"),
    path(
        "download/", DownloadQuestionTagsView.as_view(), name="download_question_tags"
    ),
    path("import-tags/", ImportTagsView.as_view(), name="import_tags"),
]

plom_server/Web_Plom/urls.py
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2022-2023 Edith Coates
# Copyright (C) 2022 Brennen Chiu
# Copyright (C) 2023-2024 Colin B. Macdonald
# Copyright (C) 2023 Julian Lapenna
# Copyright (C) 2024 Andrew Rechnitzer
# Copyright (C) 2024 Aden Chan

"""Web_Plom URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    # contains all the url path from Authentication App
    path("", include("Authentication.urls")),
    path("", include("UserManagement.urls")),
    path("", include("Profile.urls")),
    path("", include("API.urls")),
    path("", include("Base.urls")),
    path("create/", include("Preparation.urls")),
    path("create/spec/", include("SpecCreator.urls")),
    path("create/paperpdfs/", include("BuildPaperPDF.urls")),
    path("scan/", include("Scan.urls")),
    path("progress/", include("Progress.urls")),
    path("rubrics/", include("Rubrics.urls")),
    path("paper_tags/", include("Tags.urls")),
    path("finish/", include("Finish.urls")),
    path("visualization/", include("Visualization.urls")),
    path("reports/", include("Reports.urls")),
    path("task_order/", include("TaskOrder.urls")),
    path("rectangles/", include("Rectangles.urls")),
    path("identify/", include("Identify.urls")),
    path("questiontags/", include("QuestionTags.urls")),
]

# If debugging/profiling using django-silk, need to add pattern, presumably
# not during production.  See https://github.com/jazzband/django-silk
if settings.PROFILER_SILK_ENABLED:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

plom_server/QuestionTags/models.py
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024 Elisa Pan
# Copyright (C) 2024 Colin B. Macdonald
# Copyright (C) 2025 Aden Chan

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from Base.models import Tag

"""
Abstract model for associating multiple tags with a question index.

This model supports the many-to-many relationship between questions and tags.
It keeps track of multiple tags associated with a single question.
"""


class PedagogyTag(Tag):
    """Represents a tag with its description.

    Fields:
        tag_name (TextField): The name of the tag.
        description (TextField): The description of the tag.
        confidential_info (TextField): Private tag information not shown to students.
        help_threshold (FloatField): The score threshold at which help resources are shown in student report.
                                     Score is calculated per student based on the average percentage that
                                     the student got on questions tagged with a tag.
        help_resources (TextField): The help text to be shown in student report.
    """

    tag_name = models.TextField(unique=True)
    description = models.TextField(null=True, blank=True, default="")
    confidential_info = models.TextField(null=True, blank=True, default="")
    help_threshold = models.FloatField(default=0.5)
    help_resources = models.TextField(null=True, blank=True, default="")

    def __str__(self):
        """Return the tag name."""
        return str(self.tag_name)


class TmpAbstractQuestion(models.Model):
    """Represents the question index.

    This model exists to support the many-to-many relationship between questions and tags.
    It keeps track of multiple tags associated with a single question.
    """

    question_index = models.IntegerField(default=0)

    def __str__(self):
        """Return the question index."""
        return f"Question index {self.question_index}"


class QuestionTagLink(models.Model):
    """Represents a tag associated with a question by a user.

    This model links a specific pedagogy tag to a question and records the user who tagged the question
    as well as the time when the tag was added.

    Attributes:
        question (TmpAbstractQuestion): The question being tagged.
        tag (PedagogyTag): The pedagogy tag associated with the question.
        user (User): The user who tagged the question.
        time (DateTimeField): The time the tag was added.
    """

    question = models.ForeignKey(TmpAbstractQuestion, on_delete=models.CASCADE)
    tag = models.ForeignKey(PedagogyTag, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    time = models.DateTimeField(default=timezone.now)

    class Meta:
        """Meta class for QuestionTagLink model.

        Defines the constraint for the QuestionTagLink model, ensuring
        that each combination of question, tag, and user is unique.
        """

        unique_together = ("question", "tag", "user")

    def __str__(self):
        """Returns a string representation of the question-tag relationship.

        The string includes the question id, tag name, and user id who tagged the question.
        """
        user_id = self.user_id if self.user else "None"
        tag_name = self.tag.tag_name if self.tag else "None"
        return f"Question {self.question.question_index} tagged with '{tag_name}' by user {user_id}"

plom_server/QuestionTags/forms.py
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024 Elisa Pan
# Copyright (C) 2024 Colin B. Macdonald

from django import forms
from .models import PedagogyTag


class AddTagForm(forms.Form):
    """Form for adding a tag to a question.

    Fields:
        question_index: The index of the question to be tagged.
        tag_id: The ID of the tag to be added, selected from existing PedagogyTag objects.
        confidential_info: text that is shown to instructors, hidden to students.
    """

    question_index = forms.IntegerField()
    tag_id = forms.ModelChoiceField(queryset=PedagogyTag.objects.all())
    # TODO: Colin confused by CharField here and TextField in the model.
    # TODO: Elisa: CharField(widget=forms.Textarea) might be better (?)
    confidential_info = forms.CharField(required=False)


class RemoveTagForm(forms.Form):
    """Form for removing a tag from a question.

    Fields:
        question_tag_id: The ID of the question-tag link to be removed.
    """

    question_tag_id = forms.IntegerField()

plom_server/templates/Questiontags/qtags_landing.html
<!--
    SPDX-License-Identifier: AGPL-3.0-or-later
    Copyright (C) 2024 Elisa Pan
    Copyright (C) 2024 Colin B. Macdonald
    Copyright (C) 2024 Aden Chan
-->
{% extends "base/base.html" %}
{% load static %}
{% block page_heading %}
    Question Tags
{% endblock page_heading %}
{% block main_content %}
    <p>
        Tagging questions is a beta feature intended to support more
        detailed analysis during or after an assessment. For example,
        one might tag questions according to their learning objective,
        format, or topic.
    </p>
    {% if error_message %}<div class="alert alert-danger">{{ error_message }}</div>{% endif %}
    <h3>Questions</h3>
    <a href="{% url 'download_question_tags' %}?format=csv&csv_type=questions"
       class="btn btn-primary">Download Tag-Question Linking as CSV</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style=" width: 25%;">Question Index</th>
                <th style=" width: 15%;">Question Label</th>
                <th>Tags</th>
            </tr>
        </thead>
        <tbody>
            {% for index, label_str, label_html in question_label_triple %}
                <tr>
                    <td>{{ index }}</td>
                    <td>{{ label_html|safe }}</td>
                    <td id="question-tags-{{ index }}">
                        <div>
                            <span class="dropdown add-tag-button">
                                <button class="btn btn-success dropdown-toggle"
                                        type="button"
                                        data-bs-toggle="dropdown"
                                        aria-expanded="false">Add tag</button>
                                <ul class="dropdown-menu">
                                    {% for tag in tags %}
                                        <li class="p-2">
                                            <form method="post" action="{% url 'qtags_landing' %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="question_index" value="{{ index }}">
                                                <input type="hidden" name="tag_id" value="{{ tag.id }}">
                                                <button class="badge bg-success fs-6 align-middle dropdown-item py-2 text-start"
                                                        type="submit"
                                                        name="add_tag">
                                                    <i class="bi bi-plus-square pe-1"></i>{{ tag.tag_name }}
                                                </button>
                                            </form>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </span>
                            {% for question_tag in question_tags %}
                                {% if question_tag.question_index == index %}
                                    {% for qt in question_tag.questiontaglink_set.all %}
                                        <span id="tag-{{ qt.id }}" class="badge bg-primary align-middle tag">
                                            <a href="#"
                                               class="text-white"
                                               data-bs-toggle="modal"
                                               data-bs-target="#tagModal"
                                               data-tag-name="{{ qt.tag.tag_name }}"
                                               data-tag-description="{{ qt.tag.text }}">{{ qt.tag.tag_name }}</a>
                                            <form method="post" action="{% url 'qtags_landing' %}" class="d-inline">
                                                {% csrf_token %}
                                                <input type="hidden" name="question_tag_id" value="{{ qt.id }}">
                                                <button class="btn btn-primary btn-sm p-0 ms-1"
                                                        type="submit"
                                                        name="remove_tag">
                                                    <i class="bi bi-x"></i>
                                                </button>
                                            </form>
                                        </span>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'download_question_tags' %}?format=csv&csv_type=tags"
       class="btn btn-primary">Download Tags as CSV</a>
    <br />
    <h3>Manage Tags</h3>
    <button type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#createTagModal">Create Tag</button>
    <button type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#editTagModal">Edit Tag</button>
    <button type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#deleteTagModal">Delete Tag</button>
    <button type="button"
            class="btn btn-primary"
            data-bs-toggle="modal"
            data-bs-target="#importTagModal">Import Tag</button>
    <table class="table table-striped">
        <thead>
            <tr>
                <th style=" width: 25%;">Tag Name</th>
                <th>Tag Description (public)</th>
                <th>Confidential Information (private)</th>
                <th>Help Threshold</th>
                <th>Help Resources</th>
            </tr>
        </thead>
        <tbody>
            {% for tag in tags %}
                <tr>
                    <td>{{ tag.tag_name }}</td>
                    <td>{{ tag.text }}</td>
                    <td>{{ tag.confidential_info }}</td>
                    <td>{{ tag.help_threshold }}</td>
                    <td>
                        {% if tag.help_resources %}
                            Present
                        {% else %}
                            <em>Not Present</em>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "Questiontags/modal_forms.html" %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet" />
    <script>
        $(document).ready(function() {
            $('#tag_id_edit').select2({
                placeholder: 'Select or search for tags',
                allowClear: true
            });
            $('.tag-link').on('click', function() {
                var tagName = $(this).data('tag-name');
                var tagDescription = $(this).data('tag-description');
                $('#modalTagName').text(tagName);
                $('#modalTagDescription').text(tagDescription);
            });

            $('#tag_id_edit').change(function() {
                var selectedTag = $(this).val();
                var selectedTagText = $(this).find('option:selected').text().trim();
                $('#tagName_edit').val(selectedTagText);
                var selectedTagDescription = $(this).find('option:selected').data('description').trim();
                $('#text_edit').val(selectedTagDescription);
                var selectedTagconfidential_info = $(this).find('option:selected').data('confidential_info').trim();
                $('#confidential_info_edit').val(selectedTagconfidential_info);
                var selectedTagHelpThreshold = $(this).find('option:selected').data('help_threshold');
                $('#help_threshold_edit').val(selectedTagHelpThreshold);
                var selectedTagHelpResources = $(this).find('option:selected').data('help_resources').trim();
                $('#help_resources_edit').val(selectedTagHelpResources);
            });

            $('#tagModal').on('show.bs.modal', function(event) {
                var button = $(event.relatedTarget); // Button that triggered the modal
                var tagName = button.data('tag-name'); // Extract info from data-* attributes
                var tagDescription = button.data('tag-description');
                var modal = $(this);
                modal.find('#modalTagName').text(tagName);
                modal.find('#modalTagDescription').text(tagDescription);
            });
        });
    </script>
    <style>
        .select2-container {
            z-index: 9999;
        }
    </style>
{% endblock main_content %}